### ISSUE TITLE
How Are You Getting On

### ISSUE THREAD

**Issue by 5henaniganz** [Jmotsi/Justin-Project#1]
Hi Justin,

I thought I'd shoot you a message through GitHub to draw your attention to the "Issues" section. This is a great way to communicate issues in regards to your project, both from myself and you. If you find a bug or an issue it is worth writing it up here and we can discuss it and show how a collaborative workflow works.

**Comment by Jmotsi** [comment]
Thanks for letting me know about this, I have made a start on the project and making progress, ill keep you updated as I go on

**Comment by 5henaniganz** [comment]
Excellent! Thanks for keeping me posted!
